site_name: Jiajie Chen's Knowledge Base
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
    - navigation.expand
    - navigation.footer
    - navigation.indexes 
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  # - social
  - tags
  - offline
extra:
  analytics:
    provider: google
    property: G-3109FRSVTT
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Chinese
      link: /zh/
      lang: zh
copyright: Copyright &copy; 2023 Jiajie Chen
repo_url: https://github.com/jiegec/kb
edit_uri: edit/main/docs/
