site_name: Jiegec's Knowledge Base
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
    - navigation.expand
    - navigation.footer
    - navigation.indexes 
    # conflict with mkdocs-static-i18n
    # - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
default_language: en
plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh:
          name: Chinese
          build: true
          site_name: 杰哥的知识库
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  # - social
  - tags
  - offline
extra:
  analytics:
    provider: google
    property: G-3109FRSVTT
copyright: Copyright &copy; 2023 Jiajie Chen
repo_url: https://github.com/jiegec/kb
edit_uri: edit/main/docs/
