site_name: Jiegec's Knowledge Base
site_url: https://jia.je/kb
theme:
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes 
    # conflict with mkdocs-static-i18n
    # - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
plugins:
  - i18n:
      default_language: zh
      languages:
        en:
          name: English
          build: true
        zh:
          name: 中文
          build: true
          site_name: 杰哥的知识库
      nav_translations:
        zh:
          Hardware: 硬件
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - search
  # - social
  - tags
  - offline
  - wavedrom
extra:
  analytics:
    provider: google
    property: G-3109FRSVTT
copyright: Copyright &copy; 2023 Jiajie Chen
repo_url: https://github.com/jiegec/kb
edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: wavedrom
          class: wavedrom
          format: !!python/name:markdownwavedrom.plugin.fence_wavedrom_format
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/skins/default.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js

extra_css:
  - stylesheets/extra.css

